config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/:first_name', to: 'users#welcome'
  resources :gossips do
    resources :comments
    resources :likes
  end
  get '/cities/:city', to: 'cities#show'
  resources :sessions, only:[:new,:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip 
  belongs_to :tag 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city

  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messaged, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
  has_many :likes, dependent: :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:city])
    @gossips = Gossip.joins(:user).where(:users => {city: @city})
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  def index

  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
    @comments = Comment.where(gossip_id: params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new('title' => params[:title], 'content' => params[:content], 'user' => User.all.sample)
    @gossip.user = current_user
    if @gossip.save 
      redirect_to root_path, flash: {success: "Gossip cree avec success" }
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to root_path
    else 
      render :edit 
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private 

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_gossip
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
        flash[:notice] = "Tu ne peux pas like plus d'une fois voyons"
    else
      @gossip.likes.create(user_id: current_user.id)
    end
    redirect_to gossip_path(@gossip)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Tu ne peux pas unlike"
    else
      @like.destroy
    end
    redirect_to gossip_path(@gossip)
  end

  def find_like
    @like = @gossip.likes.find(params[:id])
  end
  
  private

  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id:
    params[:gossip_id]).exists?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def index
    @gossip_array = Gossip.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome
    puts "$" * 60
    puts "Voici le first name utilisé :"
    puts  params[:first_name]
    puts "$" * 60
    @user = User.new
    @user.first_name = (params["first_name"])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @cities = City.all
    @user = User.new
  end

  def create 
    @cities = City.all
    @user = User.new('first_name' => params[:first_name],'last_name' => params[:last_name], 'description' => params[:description], 'email' => params[:email], 'age' => params[:age], 'city' => City.all.sample, 'password' => params[:password])
    if @user.save 
      session[:user_id] = user.id
      redirect_to root_path, flash: {success: "Utilisateur créé avec success" }
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if  !session[:user_id].nil?
      true
    else 
      false
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/contact.html.erb
<h1>Contact#show</h1>
<p>Find me in app/views/contact/show.html.erb</p>

app/views/static_pages/index.html.erb
<section class="page-section portfolio" id="portfolio">
    <div class="container">

      <!-- Portfolio Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Liste des Gossips</h2>

      <!-- Icon Divider -->
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>

      <div class="container mb-3">
	      <%= link_to "Creer un nouveau gossip", new_gossip_path, class: 'btn btn-primary' %>
      </div>
	
      <!-- Cards Gossips -->
      <div class="row">
 	      <% @gossip_array.each do |gossip| %>
		      <div class="card m-2" style="width: 16rem;">
			    	<div class="card-body">
				  	  <h5 class="card-title"> <%= gossip.title %></h5>
  				  	<h6 class="card-subtitle mb-2 text-muted">Auteur : <%= User.find(gossip.user_id).first_name %></h6>
              <p class="card-text"><a href="/users/<%=gossip.user_id%>">En savoir plus sur l'auteur</a></p>
              <%= link_to "Voir plus sur le gossip ...", gossip_path(gossip.id), :class => "card-text" %>
              <p class="card-text">Nombre de commentaires <%= Comment.where(gossip_id: gossip.id).count %></p>
              <p class="card-text"><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                
              <% if logged_in? %>
                <% pre_like = gossip.likes.find { |like| like.user_id == log_in(current_user)} %>
                <% if pre_like %>
                  <%= button_to 'Unlike', gossip_like_path(gossip, pre_like), method: :delete %>
                <% else %>
                  <%= button_to 'Like', gossip_likes_path(gossip), method: :post %>
                <% end %>
                <% if gossip.user_id == log_in(current_user) %>
                  <a href="<%= edit_gossip_path(gossip.id) %>" class="btn btn-primary">Editer</a>
                  <a href="<%= gossip_path(gossip.id) %>" class="btn btn-danger" data-confirm="êtes-vous sûr ?" data-method="DELETE">Supprimer</a>
                <% end %>
              <% end %>
			      </div>
  		    </div>
	      <% end %>
      </div>
    </div>
  </section>

app/views/static_pages/team.html.erb
<h1>Présentation de notre équipe !</h1>
<p>voici notre équipe lol mdr 😇❤️😻</p>